### ISSUE TITLE
I have trained the models on my data and the accuracy is quite good. But now i want to use that trained model to classify a new sentence, how do i use the 'trec_gru_result.npz_FILES' to classify any new sentence?

### ISSUE THREAD

**Issue by utopiancoder** [zhegan27/sentence_classification#1]

**Comment by zhegan27** [comment]
Very sorry for my late response. I guess you have already solved this problem. But anyway, I will tell you how to do the test. Now you want to classify a new sentence, first, follow the preprocessing steps, the new sentence will divide into a sequence of tokens, by using wordtoix, the sentence now will become a sequence of numbers. By using the pred_error function inside the eval_trec_gru.py file, you should be able to get preds, which will serve as your prediction. You can wrap up the above process into a file so that you can do test easily. Hope this helps.
